services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secure_key_123!
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./faiss_index:/opt/airflow/faiss_index
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secure_key_123!
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./faiss_index:/opt/airflow/faiss_index
    command: scheduler

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: ollama_chatbot_api
    ports:
      - "8000:8000"
    volumes:
      - ./faiss_index:/app/faiss_index
      - ./scripts:/app/scripts
      - ./data:/app/data
    command: uvicorn scripts.ollama_agent_api:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:

